### ISSUE TITLE
Could not run faceDetection.ts

### ISSUE THREAD

**Issue by tobisaki** [justadudewhohacks/face-api.js#142]
I hope you to tell me, error reason why.
here wrote, environment, actions and result
thanks
------------- environment -------------
$ uname -rv
4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018

$ node -v
v11.2.0

$ npm ls typescript ts-node -g
/usr/local/lib
├── ts-node@7.0.1
└── typescript@3.1.6

------------- environment -------------

------------- tried-and-result -------------
$ cd /home/tobisaki/try2
$ git clone https://github.com/justadudewhohacks/face-api.js.git
$ cd face-api.js/examples/examples-nodejs/

$ ls -la
合計 64
drwxrwxr-x  4 tobisaki tobisaki  4096 11月 20 08:36 .
drwxrwxr-x  6 tobisaki tobisaki  4096 11月 19 23:19 ..
drwxrwxr-x  2 tobisaki tobisaki  4096 11月 19 23:19 commons
-rw-rw-r--  1 tobisaki tobisaki   479 11月 19 23:19 faceDetection.ts
-rw-rw-r--  1 tobisaki tobisaki   704 11月 19 23:19 faceLandmarkDetection.ts
-rw-rw-r--  1 tobisaki tobisaki  1649 11月 19 23:19 faceRecognition.ts
drwxrwxr-x 88 tobisaki tobisaki  4096 11月 20 09:07 node_modules
-rw-rw-r--  1 tobisaki tobisaki 28902 11月 20 08:36 package-lock.json
-rw-rw-r--  1 tobisaki tobisaki   197 11月 20 08:36 package.json

$ npm i
$ ts-node faceDetection.ts

/usr/local/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
faceDetection.ts(3,16): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
faceDetection.ts(5,26): error TS2339: Property 'loadFromDisk' does not exist on type 'SsdMobilenetv1'.
faceDetection.ts(10,23): error TS2339: Property 'createCanvasFromMedia' does not exist on type 'typeof import("/home/tobisaki/try2/face-api.js/src/index")'.
faceDetection.ts(11,11): error TS2339: Property 'drawDetection' does not exist on type 'typeof import("/home/tobisaki/try2/face-api.js/src/index")'.

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)

------------- tried-and-result -------------

**Comment by tobisaki** [comment]
So Sorry!!

I overlook faild packages when npm inisatll.
Vulnerability Audited package was found by command(npm audit).
                       === npm audit security report ===                        
                                                                                
\# Run  npm install --save-dev karma-typescript@3.0.13  to resolve 1 vulnerability
...

It was fixed by command(npm audit fix).

But ...My environment not have GUP. Result was
$ ts-node faceDetection.ts 
2018-11-20 15:06:58.359383: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
cpu backend was already registered. Reusing existing backend
2018-11-20 15:07:02.048092: W tensorflow/core/framework/allocator.cc:113] Allocation of 16777216 exceeds 10% of system memory.
2018-11-20 15:07:02.068154: W tensorflow/core/framework/allocator.cc:113] Allocation of 16777216 exceeds 10% of system memory.
2018-11-20 15:07:02.082211: W tensorflow/core/framework/allocator.cc:113] Allocation of 16777216 exceeds 10% of system memory.

**Comment by lsim** [comment]
I'm seeing the same problem. The suggested fix doesn't seem to apply in my case. This is what I get (after manually installing tslib, which it was complaining about first):

```
% ts-node -v
ts-node v7.0.1
node v11.2.0
typescript v3.2.1

los@ssdbuntu:~/src/face-api.js/examples/examples-nodejs^master ±
% ts-node faceDetection.ts

/home/los/n/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
faceDetection.ts(5,26): error TS2339: Property 'loadFromDisk' does not exist on type 'SsdMobilenetv1'.
faceDetection.ts(10,23): error TS2339: Property 'createCanvasFromMedia' does not exist on type 'typeof import("/home/los/src/face-api.js/src/index")'.
faceDetection.ts(11,11): error TS2339: Property 'drawDetection' does not exist on type 'typeof import("/home/los/src/face-api.js/src/index")'.

    at createTSError (/home/los/n/lib/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/los/n/lib/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/los/n/lib/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/los/n/lib/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/los/n/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)

```

Any help would be appreciated
