### ISSUE TITLE
nodejs examples can't working

### ISSUE THREAD

**Issue by hwanpenn** [justadudewhohacks/face-api.js#200]
macos    node v10.7.0     npm 6.6.0     tfjs-core "0.13.8"  

git clone https://github.com/justadudewhohacks/face-api.js.git

cd face-api.js/examples/examples-nodejs
npm i

ts-node faceDetection.ts

localhost:examples-nodejs hwanpenn$ ts-node faceDetection.ts
2019-01-23 15:48:46.382968: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPUsupports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
cpu backend was already registered. Reusing existing backend
(node:33079) UnhandledPromiseRejectionWarning: TypeError: trackerFn(...).nextTensorId is not a function
    at new Tensor (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/tensor.ts:415:27)
    at Function.Tensor.make (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/tensor.ts:430:12)
    at Object.tensor (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/tensor_ops.ts:99:17)
    at _loop_1 (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/io_utils.ts:129:15)
    at Object.decodeWeights (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:132:9)
    at /Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:221:13
    at Array.forEach (<anonymous>)
    at /Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:216:22
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/io/weights_loader.ts:197:25)
(node:33079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**similar with Can´t get nodejs examples working #164  ，but my tfjs-core version is right， i dont know how to fix it  ，Browser examples works fine.**

**Comment by justadudewhohacks** [comment]
Try to clean your node_modules and start over with a fresh npm install. The error message does not come from face-api.js, but from tfjs-core.

**Comment by xperiafan13-rom** [comment]
Some error

**Comment by hwanpenn** [comment]
thanks @justadudewhohacks  ， love you ^_^, with your suggest i fix that，but。。。

TSError: ⨯ Unable to compile TypeScript:
error TS2468: Cannot find global value 'Promise'.
faceDetection.ts(3,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

it is not from face-api.js，now im trying fix this

**Comment by hwanpenn** [comment]
continue   “This syntax requires an imported helper but module 'tslib' cannot be found.”  and i found face-api.js/package.json has  “  "tslib": "^1.9.3"”   

so i go /face-api.js/ and npm install  ，

and found # Run  npm install --save-dev karma-typescript@3.0.13  to resolve 1 vulnerability with npm audit     then npm audit fix （same with Could not run faceDetection.ts #142） 

it seem work  ，no “TSError: ⨯ Unable to compile TypeScript:” again，
but new error  （）：
2019-01-28 13:43:14.462031: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPUsupports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
cpu backend was already registered. Reusing existing backend
(node:88557) UnhandledPromiseRejectionWarning: TypeError: trackerFn(...).nextTensorId is not a function
    at new Tensor (/Users/hwanpenn/Downloads/hwanpenn/face01/node_modules/@tensorflow/tfjs-core/src/tensor.ts:415:27)

Isn't that my first mistake?   Wrapped around a large circle ， fuck...

**Comment by hwanpenn** [comment]
i am dying ， i fix the problem upstairs，and i have a new one again。。。

2019-01-28 15:40:11.349408: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
cpu backend was already registered. Reusing existing backend

/Users/hwanpenn/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
../../src/ssdMobilenetv1/outputLayer.ts(73,7): error TS2345: Argument of type '[number, number | undefined]' is not assignable to parameter of type 'number[] | [number, number, number] | [number, number, number, number] | [number, number] | [number] | [number, number, number, number, number] | [number, number, number, number, number, number]'.
  Type '[number, number | undefined]' is not assignable to type '[number, number]'.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.

    at createTSError (/Users/hwanpenn/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:228:12)
    at getOutput (/Users/hwanpenn/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:334:40)
    at Object.compile (/Users/hwanpenn/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:367:11)
    at Module.m._compile (/Users/hwanpenn/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:413:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by justadudewhohacks** [comment]
Hold on for a second. 

> (node:33079) UnhandledPromiseRejectionWarning: TypeError: trackerFn(...).nextTensorId is not a function
> at new Tensor (/Users/hwanpenn/Documents/hwanpenn/face-api.js/node_modules/@tensorflow/tfjs-core/src/tensor.ts:415:27)

I think this is an issue with tfjs-node@0.1.19, which is the current in the package.json of the nodejs examples. It should actually be tfjs-node@0.1.21 (same as in the root package.json).

> TSError: ⨯ Unable to compile TypeScript:
> ../../src/ssdMobilenetv1/outputLayer.ts(73,7): error TS2345: Argument of type '[number, number | undefined]' is not assignable to parameter of type 'number[] | [number, number, number] | [number, number, number, number] | [number, number] | [number] | [number, number, number, number, number] | [number, number, number, number, number, number]'.
> Type '[number, number | undefined]' is not assignable to type '[number, number]'.
> Type 'number | undefined' is not assignable to type 'number'.
> Type 'undefined' is not assignable to type 'number'.

This is a typescript 3 specific error, which indicates that you are not using ts-node v7.0.1 anymore. I am currently updating the dependencies of face-api.js including upgrading the typescript version to latest.

**Comment by hwanpenn** [comment]
1.git clone https://github.com/justadudewhohacks/face-api.js.git
2.examples/examples-nodejs/package.json "@tensorflow/tfjs-node": "^0.1.19"-->"^0.1.21"
3.cd face-api.js
    npm install    （fix tslib）
    npm audit fix       （add karma-typescript@3.0.13）
4.cd face-api.js/examples/examples-nodejs
    npm install
    ts-node faceDetection.ts

 **you are right @justadudewhohacks ，It should be tfjs-node@0.1.21 ，it works ，now i love you more**
