### ISSUE TITLE
Unable to run node facedetection.js

### ISSUE THREAD

**Issue by frajos100** [justadudewhohacks/face-api.js#208]
Hi,
Using typescript had executed the command 
tsc faceDetection.ts
faceDetection.ts(5,7): error TS1005: ';' expected.
faceDetection.ts(7,9): error TS1005: ';' expected.
faceDetection.ts(9,21): error TS1005: ',' expected.
faceDetection.ts(9,27): error TS1005: ',' expected.
faceDetection.ts(9,37): error TS1005: '=' expected.
faceDetection.ts(10,28): error TS1005: ',' expected.
faceDetection.ts(10,35): error TS1005: ',' expected.
faceDetection.ts(10,50): error TS1005: '=' expected.
faceDetection.ts(12,50): error TS1005: ',' expected.
faceDetection.ts(12,53): error TS1005: '=' expected.

While executing the second command "node facedetection.js" getting the below error. Need your help to resolve the error inorder to check how it runs.
node facedetection.js
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module './commons'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (root path\FaceAPI\face-api.js-master\face-api.js-master\examples\examples-nodejs\facedetection.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)

**Comment by justadudewhohacks** [comment]
What's the typescript version you are using? Should work with a recent version. You can also run the examples directly with ts-node.
