### ISSUE TITLE
React live webcam example

### ISSUE THREAD

**Issue by julesmoretti** [justadudewhohacks/face-api.js#374]
Hello there,

I was looking at your live demos and did not find the codebase for those. I am Interested in the webcam live demo version but for react.

Could you please either create an example page or point to the code base for that live demo?

And not sure also where the models are currently stored in your repo.

Thank you for the help, this is a very cool library!

Keep it up please.

**Comment by julesmoretti** [comment]
Especially considering that:

```
[jules:...js/examples/examples-nodejs]$ ts-node faceDetection.ts                                                                                              (master✱) 
zsh: command not found: ts-node
[jules:...js/examples/examples-nodejs]$ tsc faceDetection.ts                                                                                                  (master✱) 
zsh: command not found: tsc
[jules:...js/examples/examples-nodejs]$ node faceDetection.js                                                                                                 (master✱) 
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/Users/jules/Git/face-api.js/examples/examples-nodejs/faceDetection.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by Panepo** [comment]
Hi @julesmoretti 

[Here](https://panepo.github.io/Uzuki/)'s a face-api.js demo with react.

The code for learning faces and recognizing via webcam can be found [here](https://github.com/Panepo/Uzuki/blob/master/src/pages/Train/Train.jsx) and [here](https://github.com/Panepo/Uzuki/blob/master/src/pages/Sensor/Sensor.jsx).

**Comment by linhbkhn95** [comment]
i has project Nextjs 
https://github.com/linhbkhn95/face-frontend-nextjs

**Comment by julesmoretti** [comment]
@Panepo - thank you for the info, the [link](https://panepo.github.io/Uzuki/) you provided points to a pink page. Can you point out the working demo of the two other links ([1](https://github.com/Panepo/Uzuki/blob/master/src/pages/Train/Train.jsx), [2](https://github.com/Panepo/Uzuki/blob/master/src/pages/Sensor/Sensor.jsx)) you added?

@linhbkhn95 - Thank you for your repo, I tried running it and it does not work sadly.

So far I have a codebase that seems to work but I do not think it is up to date as the `drawLandmarks` is not aligned with my face. Also I am not sure how to have the landing box over my face.... Anyways I would love to have the bounding boxes over the webcam live feed but my code is dated and not very clean... any pointers would be great.

Here is the modified code from this repo: https://github.com/BonnieMilian/face-api-webcam-react
```
import React, { Component } from 'react';
import './App.css';
import * as faceapi from 'face-api.js';
import styled from 'styled-components';
// import WebCamPicture from './components/WebCamPicture.js';

import Webcam from 'react-webcam';

const videoConstraints = {
  width: 350,
  height: 350,
  facingMode: 'user',
};

const MODEL_URL = '/models'
const minConfidence = 0.6
// const testImage = '/img/bonnie.jpg'

const MainContainer = styled.div`
  background: red;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  flex-direction: column;
`;

const TopRowDiv = styled.div`
  height: ${props => props.height}%;
  width: inherit;
  background: yellow;
  flex-direction: row;
  justify-content: flex-start;
  display: flex;
`;

const BottomRowDiv = styled.div`
  background: green;
  width: inherit;
  flex: 1;
`;

const HorizontalRange = styled.input`
  position: absolute;
  width: 100%;
  top: 0;
  left: 0;
`;

const VerticalRange = styled.input`
  height: 100%;
  position: absolute;
  transform: rotate(90deg);
  width: 100vh;
  right: -50vh;
  // width: 10px;
  top: 0;
  // writing-mode: bt-lr; /* IE */
  // -webkit-appearance: slider-vertical; /* WebKit */
`;

const VideoDiv = styled.div`
  text-align: center;
  width: ${props => props.width}%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  // flex-direction: row;
  background: #0f2338; /* Old browsers */
  background: -moz-linear-gradient(top, #0f2338 0%, #2d73aa 100%); /* FF3.6-15 */
  background: -webkit-linear-gradient(top, #0f2338 0%,#2d73aa 100%); /* Chrome10-25,Safari5.1-6 */
  background: linear-gradient(to bottom, #0f2338 0%,#2d73aa 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
  overflow: hidden;
`;

const Canvas = styled.canvas `
  position: absolute;
  border: 1px solid red;
`;

export default class App extends Component {
  constructor(props){
    super(props);
    this.fullFaceDescriptions = null;
    this.canvas = React.createRef();
    this.canvasPicWebCam = React.createRef();
    this.webcam = React.createRef();
    this.state = {
      width: 50,
      height: 50,
      imageSrc: null,
    }
  }

  async componentDidMount() {
    await this.loadModels();
    // const testImageHTML = document.getElementById('test')
    // this.drawHTMLImage(this.canvas.current,testImageHTML,296,296);
    // await this.getFullFaceDescription(this.canvas.current);
    // this.drawDescription(this.canvas.current);

    setInterval(() => {
      this.capture();
    }, 1000);
  }

  async loadModels () {
    //await faceapi.loadModels(MODEL_URL)
    await faceapi.loadFaceDetectionModel(MODEL_URL)
    await faceapi.loadFaceLandmarkModel(MODEL_URL)
    await faceapi.loadFaceRecognitionModel(MODEL_URL)
  }

  capture = () => {
    const imageSrc = this.webcam.current.getScreenshot();
    //console.log("Take Picture");
    // this.props.landmarkPicture(imageSrc);
    // this.setState({ imageSrc });
    this.landmarkWebCamPicture(imageSrc);
  };

  landmarkWebCamPicture = (picture) => {
    const ctx = this.canvasPicWebCam.current.getContext("2d");
    var image = new Image();
    image.onload = async () => {
      ctx.drawImage(image,0,0);
      await this.getFullFaceDescription(this.canvasPicWebCam.current);
      this.drawDescription(this.canvasPicWebCam.current);
    };
    image.src = picture;
  }

  getFullFaceDescription = async (canvas) => {
    console.log(canvas);
    this.fullFaceDescriptions = await faceapi
    .allFaces(canvas, minConfidence);
    console.log(this.fullFaceDescriptions);
  }

  drawDescription = (canvas) => {
    this.fullFaceDescriptions.forEach((fd, i) => {
      console.log("drawDescription", i, fd);
      faceapi.drawLandmarks(canvas, fd.landmarks, { drawLines: false })
    })
  }

  drawHTMLImage(canvas,image,width,height){
    const ctx = canvas.getContext("2d");
    ctx.drawImage(image,0,0,width,height);
  }

  render() {
    return (
      <div className="App" >
        <MainContainer>
          <VerticalRange
            type="range"
            name="points"
            min="0"
            max="100"
            step="0.1"
            value={this.state.height}
            onChange={(event) => this.setState({ height: event.target.value })}
          />
          <HorizontalRange
            type="range"
            name="points"
            min="0"
            max="100"
            step="0.1"
            value={this.state.width}
            onChange={(event) => this.setState({ width: event.target.value })}
          />
          <TopRowDiv
            height={this.state.height}
          >
            <VideoDiv
              width={this.state.width}
            >
              <Webcam
                audio={false}
                height={350}
                ref={this.webcam}
                screenshotFormat="image/jpeg"
                width={350}
                videoConstraints={videoConstraints}
              />
              <Canvas ref={this.canvasPicWebCam} width={350} height={350} />
            </VideoDiv>
          </TopRowDiv>
          <BottomRowDiv />
        </MainContainer>
      </div>
    );
  }
}

```

Thank you

**Comment by Panepo** [comment]
Hi @julesmoretti 

A pink page? Read the readme and get [instructions](https://github.com/Panepo/Uzuki)
If there's something different with the screenshot, please use a Tensorflow.js supported browsers like Chrome and Firefox, and javascript should be enabled.

**Comment by julesmoretti** [comment]
@Panepo - thank you, I see what you mean its a very sophisticated demo you made, I am just looking for a very stripped down version of it. But will look through your code thank you.

**Comment by justadudewhohacks** [comment]
> Could you please either create an example page or point to the code base for that live demo?

I am not going to add react examples to this repo sorry, there is no react specific things about this API, so by understanding the existing examples, you should be able to integrate face-api.js with React.

> And not sure also where the models are currently stored in your repo.

They are located in the [weights](https://github.com/justadudewhohacks/face-api.js/tree/master/weights) folder.
