### ISSUE TITLE
npm run test fails with (404) Not Found, from url: weights_uncompressed/face_landmark_68_model.weights

### ISSUE THREAD

**Issue by subtleGradient** [justadudewhohacks/face-api.js#427]
```
$ npm run test

> face-api.js@0.21.0 test /Users/taylott/Projects/face-api.js
> karma start

29 09 2019 11:39:22.349:WARN [filelist]: Pattern "/Users/taylott/Projects/face-api.js/weights_uncompressed/**/*" does not match any file.
29 09 2019 11:39:22.357:WARN [filelist]: Pattern "/Users/taylott/Projects/face-api.js/weights_unused/**/*" does not match any file.
29 09 2019 11:39:22.770:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.6.3
29 09 2019 11:39:29.286:INFO [compiler.karma-typescript]: Compiled 163 files in 6417 ms.
29 09 2019 11:39:31.384:INFO [bundler.karma-typescript]: Bundled imports for 160 file(s) in 1594 ms.
29 09 2019 11:39:33.000:WARN [karma]: No captured browser, open http://localhost:9876/
29 09 2019 11:39:33.085:INFO [karma-server]: Karma v4.3.0 server started at http://0.0.0.0:9876/
29 09 2019 11:39:33.085:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
29 09 2019 11:39:33.096:INFO [launcher]: Starting browser Chrome
29 09 2019 11:39:36.086:INFO [Chrome 77.0.3865 (Mac OS X 10.14.3)]: Connected on socket 36m6lvhEuAIMS1riAAAA with id 21459220
Chrome 77.0.3865 (Mac OS X 10.14.3) LOG: 'running tests on WebGL backend'

Chrome 77.0.3865 (Mac OS X 10.14.3): Executed 3 of 179 SUCCESS (0 secs / 0.007 secs)
Chrome 77.0.3865 (Mac OS X 10.14.3) faceLandmark68Net, uncompressed uncompressed weights computes face landmarks for squared input FAILED
	Error: FaceLandmark68Net - load model before inference
	    at FaceLandmark68Net.FaceProcessor.runNet (src/faceProcessor/FaceProcessor.ts:40:13 <- src/faceProcessor/FaceProcessor.js:68:31)
	    at src/faceLandmarkNet/FaceLandmark68NetBase.ts:60:24 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:123:41
	    at /var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13546:22
	    at Engine.scopedRun (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13556:23)
	    at Engine.tidy (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13545:21)
	    at Object.tidy (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:964:28)
	    at FaceLandmark68NetBase.forwardInput (src/faceLandmarkNet/FaceLandmark68NetBase.ts:59:15 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:120:31)
	    at src/faceLandmarkNet/FaceLandmark68NetBase.ts:76:29 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:200:61
	    at /var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13546:22
	    at Engine.scopedRun (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13556:23)
Chrome 77.0.3865 (Mac OS X 10.14.3) faceLandmark68Net, uncompressed uncompressed weights computes face landmarks for rectangular input FAILED
	Error: FaceLandmark68Net - load model before inference
	    at FaceLandmark68Net.FaceProcessor.runNet (src/faceProcessor/FaceProcessor.ts:40:13 <- src/faceProcessor/FaceProcessor.js:68:31)
	    at src/faceLandmarkNet/FaceLandmark68NetBase.ts:60:24 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:123:41
	    at /var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13546:22
	    at Engine.scopedRun (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13556:23)
	    at Engine.tidy (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13545:21)
	    at Object.tidy (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:964:28)
	    at FaceLandmark68NetBase.forwardInput (src/faceLandmarkNet/FaceLandmark68NetBase.ts:59:15 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:120:31)
	    at src/faceLandmarkNet/FaceLandmark68NetBase.ts:76:29 <- src/faceLandmarkNet/FaceLandmark68NetBase.js:200:61
	    at /var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13546:22
	    at Engine.scopedRun (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:13556:23)
Chrome 77.0.3865 (Mac OS X 10.14.3) ERROR
  An error was thrown in afterAll
  Error: failed to fetch: (404) Not Found, from url: weights_uncompressed/face_landmark_68_model.weights
      at Object.<anonymous> (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:22185:31)
      at step (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:142:27)
      at Object.next (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:123:57)
      at fulfilled (/var/folders/_c/r39j1sgj7qzdf184by_ctp2m0000gn/T/karma-typescript-bundle-720674ME1lwIQubwH.js:113:62)
Chrome 77.0.3865 (Mac OS X 10.14.3): Executed 5 of 179 (2 FAILED) ERROR (0.087 secs / 0.013 secs)
```

**Comment by justadudewhohacks** [comment]
`npm run test` runs all testcases including tests for uncompressed models, which will fail if you didn't download the uncompressed model weights manually.

Try the following scripts, which are also used by the CI:

```
"test-exclude-uncompressed": "set EXCLUDE_UNCOMPRESSED=true&& karma start",
"test-browser-exclude-uncompressed": "set EXCLUDE_UNCOMPRESSED=true&& karma start --single-run",
"test-node-exclude-uncompressed": "set EXCLUDE_UNCOMPRESSED=true&& npm run test-node",
```
