### ISSUE TITLE
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

### ISSUE THREAD

**Issue by EasonWang01** [justadudewhohacks/face-api.js#450]
Logs: 

```
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 4
2019-10-24 13:34:37.471423: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

/usr/local/lib/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
commons/faceDetection.ts:19:10 - error TS2367: This condition will always return 'false' since the types 'NeuralNetwork<any>' and 'SsdMobilenetv1' have no overlap.

19   return net === faceapi.nets.ssdMobilenetv1
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
commons/faceDetection.ts:21:8 - error TS2367: This condition will always return 'false' since the types 'NeuralNetwork<any>' and 'TinyFaceDetector' have no overlap.

21     : (net === faceapi.nets.tinyFaceDetector
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
commons/faceDetection.ts:27:60 - error TS2345: Argument of type 'SsdMobilenetv1' is not assignable to parameter of type 'NeuralNetwork<any>'.
  Types of property 'extractParamsFromWeigthMap' are incompatible.
    Type '(weightMap: NamedTensorMap) => { params: NetParams; paramMappings: ParamMapping[]; }' is not assignable to type '(weightMap: NamedTensorMap) => { params: any; paramMappings: ParamMapping[]; }'.
      Types of parameters 'weightMap' and 'weightMap' are incompatible.
        Type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor_types").NamedTensorMap' is not assignable to type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor_types").NamedTensorMap'.
          Index signatures are incompatible.
            Type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-reco...' is not assignable to type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank>'.
              Types of property 'flatten' are incompatible.
                Type '() => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-imag...' is not assignable to type '() => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R1>'.
                  Type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-reco...' is not assignable to type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R1>'.
                    Types of property 'asScalar' are incompatible.
                      Type '() => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-imag...' is not assignable to type '() => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R0>'.
                        Type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-reco...' is not assignable to type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R0>'.
                          Types of property 'as2D' are incompatible.
                            Type '(rows: number, columns: number) => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-...' is not assignable to type '(rows: number, columns: number) => import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core...'.
                              Type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-reco...' is not assignable to type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R2>'.
                                Types of property 'asType' are incompatible.
                                  Type '<T extends import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs...' is not assignable to type '<T extends import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R2>>(...'.
                                    The 'this' types of each signature are incompatible.
                                      Type 'T' is not assignable to type 'Tensor<Rank.R2>'.
                                        Property 'relu6' is missing in type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/dist/types").Rank.R2>' but required in type 'import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor<import("/Users/yicheng/opencvTest/face-api.js/examples/examples-nodejs/node_modules/face-api.js/node_modules/tfjs-image-reco...'.

27 export const faceDetectionOptions = getFaceDetectorOptions(faceDetectionNet)
                                                              ~~~~~~~~~~~~~~~~

  node_modules/face-api.js/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/tensor.d.ts:540:5
    540     relu6<T extends Tensor>(this: T): T;
            ~~~~~
    'relu6' is declared here.

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:357:34)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:415:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:493:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by justadudewhohacks** [comment]
What version of typescript are you using? face-api.js is compiled with TS 3.6.3, so upgrade your TS compiler.

**Comment by EasonWang01** [comment]
I'm using the latest version v3.6.4.
<img width="110" alt="螢幕快照 2019-10-29 上午9 54 15" src="https://user-images.githubusercontent.com/11001914/67731140-30782600-fa32-11e9-81ee-88bea35b2dd6.png">

**Comment by yugasun** [comment]
Me too...

**Comment by jirayudech** [comment]
Me too 3.7.4

**Comment by shanurrahman-gcsns** [comment]
I am on 3.9.3 and still get the same issue
```
 Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-21 16:00:24.813860: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1071ef570 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-21 16:00:24.813925: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

**Comment by RezaRahmati** [comment]
I am using Typescript 4.1.3 and still same message

> Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2, cpu backend was already registered. Reusing existing backend factory.
