### ISSUE TITLE
I'm having a issue in running the example

### ISSUE THREAD

**Issue by MukeshKalaga** [justadudewhohacks/face-api.js#488]
I'm having following issue,

cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
Error: The specified module could not be found.

<MyLoc>\face-api.js\examples\examples-nodejs\node_modules\@tensorflow\tfjs-node\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)

**Comment by justadudewhohacks** [comment]
This error doesn't come from face-api.js, it comes from tfjs-node. Please make sure you are using the same tfjs-core and tfjs-node version as suggested in the package.json of the example.
