### ISSUE TITLE
Error GPU usage(CUDNN_STATUS_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by FedorovP777** [justadudewhohacks/face-api.js#534]
"@tensorflow/tfjs-node-gpu": "^1.4.0"
"face-api.js": "0.22.0"
Driver Version: 440.48.02    CUDA Version: 10.2
GeForce GTX 1650
Ubuntu 18.04
I try run Win10 and have some problem
`
 nodemon --exec ./node_modules/.bin/ts-node -- ./src/index.ts

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `./node_modules/.bin/ts-node ./src/index.ts`
2020-01-25 00:51:57.358207: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-25 00:51:57.388648: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2020-01-25 00:51:57.390138: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4ab0c30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-25 00:51:57.390202: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-25 00:51:57.391997: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-25 00:51:57.811615: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.811823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
2020-01-25 00:51:57.811958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-25 00:51:57.812750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-25 00:51:57.813434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-25 00:51:57.813587: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-25 00:51:57.814517: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-25 00:51:57.815262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-25 00:51:57.817569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-25 00:51:57.817619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.817815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.817973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-01-25 00:51:57.817988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-25 00:51:57.856422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-25 00:51:57.856459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-01-25 00:51:57.856464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-01-25 00:51:57.856537: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.856729: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.856907: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-25 00:51:57.857088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3548 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5)
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
raven@2.6.4 alert: no DSN provided, error reporting disabled
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
mtcnn is deprecated and will be removed soon
2020-01-25 00:52:20.197202: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-25 00:52:20.917478: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-01-25 00:52:20.921141: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
(node:5734) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 2
Message: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
    at NodeJSKernelBackend.executeSingleOutput (/home/user/aa/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:193:43)
    at NodeJSKernelBackend.conv2d (/home/user/aa/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:744:21)
    at engine_1.ENGINE.runKernelFunc.x (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/conv.ts:205:25)
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:586:31
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:424:20
    at Engine.scopedRun (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:435:19)
    at Engine.tidy (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:422:17)
    at kernelFunc (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:586:20)
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:599:23
    at Engine.scopedRun (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:435:19)
    at Engine.runKernelFunc (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:596:10)
    at conv2d_ (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/conv.ts:204:22)
    at Object.conv2d (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:45:24)
    at /home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/pointwiseConvLayer.ts:12:18
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:424:20
    at Engine.scopedRun (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:435:19)
    at Engine.tidy (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:422:17)
    at Object.tidy (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/globals.ts:182:17)
    at Object.pointwiseConvLayer (/home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/pointwiseConvLayer.ts:10:13)
    at /home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/mobileNetV1.ts:37:15
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:424:20
    at Engine.scopedRun (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:435:19)
    at Engine.tidy (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:422:17)
    at Object.tidy (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/globals.ts:182:17)
    at Object.mobileNetV1 (/home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/mobileNetV1.ts:34:13)
    at /home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/SsdMobilenetv1.ts:35:24
    at /home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:424:20
    at Engine.scopedRun (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:435:19)
    at Engine.tidy (/home/user/aa/node_modules/@tensorflow/tfjs-core/src/engine.ts:422:17)
    at Object.tidy (/home/user/aa/node_modules/face-api.js/node_modules/@tensorflow/tfjs-core/src/globals.ts:182:17)
    at SsdMobilenetv1.forwardInput (/home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/SsdMobilenetv1.ts:31:15)
    at SsdMobilenetv1.<anonymous> (/home/user/aa/node_modules/face-api.js/src/ssdMobilenetv1/SsdMobilenetv1.ts:62:14)
    at step (/home/user/aa/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/user/aa/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/user/aa/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:5734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
`

**Comment by FedorovP777** [comment]
Helped `export TF_FORCE_GPU_ALLOW_GROWTH=true`
