### ISSUE TITLE
Cannot read property 'monkeyPatch' of undefined

### ISSUE THREAD

**Issue by ShivamJoker** [justadudewhohacks/face-api.js#566]
I tried following the docs for nodejs and it's giving me error

Code
```js
// import nodejs bindings to native tensorflow,
// not required, but will speed up things drastically (python required)
// import "@tensorflow/tfjs-node";

// implements nodejs wrappers for HTMLCanvasElement, HTMLImageElement, ImageData
import * as canvas from "canvas";

import * as faceapi from "face-api.js";

const app = async () => {
  // patch nodejs environment, we need to provide an implementation of
  // HTMLCanvasElement and HTMLImageElement
  const { Canvas, Image, ImageData } = canvas;

  faceapi.env.monkeyPatch({ Canvas, Image, ImageData });

  // await faceapi.loadSsdMobilenetv1Model('/models')
  await faceapi.loadTinyFaceDetectorModel("/models");
  const input = await canvas.loadImage("./faces.jpeg");

  const detections = await faceapi.detectAllFaces(input);
  console.log(detections);
};
app();
```

`node version v13.8.0`
`macOS latest catalina`

❯ node index.js                                          
(node:37624) ExperimentalWarning: The ESM module loader is experimental.
(node:37624) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'monkeyPatch' of undefined
    at app (file:///Users/shivam/Documents/web/face-api-js/index.js:15:15)
    at file:///Users/shivam/Documents/web/face-api-js/index.js:24:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
(node:37624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by acuntex** [comment]
Write the import as following:

`import faceapi from "face-api.js";`

**Comment by ali-tafakkori** [comment]
I have same issues.
