### ISSUE TITLE
Can't run or compile nodejs examples

### ISSUE THREAD

**Issue by asystat** [justadudewhohacks/face-api.js#626]
I'm having trouble running the nodejs examples.

```
node -v 
v12.16.3
```
```
tsc -v
Version 3.9.3
```
```
ts-node -v
v8.10.2
```
After installing all dependencies, not ts-node nor tsc works. These are the results from running:
**ts-node ageAndGenderRecognition.ts**
```
face-api.js/examples/examples-nodejs/node_modules/@tensorflow/tfjs-backend-cpu/src/backend_cpu.ts:24
const nonMaxSuppressionV3 = kernel_impls.nonMaxSuppressionV3;
                                         ^
TypeError: Cannot read property 'nonMaxSuppressionV3' of undefined
    at Object.<anonymous> (/Users/seba/Programming/node/face-api.js/examples/examples-nodejs/node_modules/@tensorflow/tfjs-backend-cpu/src/backend_cpu.ts:24:42)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/seba/Programming/node/face-api.js/examples/examples-nodejs/node_modules/@tensorflow/tfjs/dist/tf.node.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```

Also when trying to compile the ts files by running: 
**tsc ageAndGenderRecognition.ts**
```
node_modules/@tensorflow/tfjs-backend-cpu/dist/backend_cpu.d.ts:64:111 - error TS2694: Namespace '"/Users/seba/Programming/node/face-api.js/examples/examples-nodejs/node_modules/@tensorflow/tfjs-core/dist/backends/backend_util"' has no exported member 'FusedBatchMatMulConfig'.

64     fusedBatchMatMul({ a, b, transposeA, transposeB, bias, activation, preluActivationWeights }: backend_util.FusedBatchMatMulConfig): Tensor3D;
                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tensorflow/tfjs-backend-cpu/dist/kernels/Max_impl.d.ts:17:20 - error TS2305: Module '"../../../tfjs-core/dist"' has no exported member 'TypedArray'.

17 import { DataType, TypedArray } from '@tensorflow/tfjs-core';
                      ~~~~~~~~~~

node_modules/@tensorflow/tfjs-backend-cpu/dist/kernels/Transpose_impl.d.ts:17:20 - error TS2305: Module '"../../../tfjs-core/dist"' has no exported member 'TypedArray'.

17 import { DataType, TypedArray } from '@tensorflow/tfjs-core';
                      ~~~~~~~~~~

node_modules/@tensorflow/tfjs-backend-webgl/dist/backend_webgl.d.ts:26:10 - error TS2305: Module '"../../tfjs-core/dist"' has no exported member 'BackendValues'.

26 import { BackendValues } from '@tensorflow/tfjs-core';
...
...
```

It seems to me that it has something to do with the versions I'm running maybe?

**Comment by asystat** [comment]
OK I followed this instructions and ended up working
https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs

Some of the steps can't be done thoug as they are for linux.
