### ISSUE TITLE
Error: FaceRecognizer.constructor - expected inputs to be of type LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array | Array<LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array>

### ISSUE THREAD

**Issue by oebilgen** [justadudewhohacks/face-api.js#652]
The [documentation for FaceMatcher](https://github.com/justadudewhohacks/face-api.js#face-recognition-by-matching-descriptors) throws an exception in NodeJS. Although `faceapi.detectAllFaces` finds faces, `new faceapi.FaceMatcher(faceResults)` throws an exception. Can you please let us know what we should be doing here?

Code:
```
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelUrl)
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelUrl)
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelUrl)

  const faceBase64 = 'data:image/jpg;base64,' + fs.readFileSync(`./tests/data/face1.jpg`, {encoding: 'base64'})
  const faceImage = new Image()
  faceImage.src = faceBase64
  const faceResults = await faceapi.detectAllFaces(faceImage)
      .withFaceLandmarks()
      .withFaceDescriptors()

  if (!faceResults.length) { // length is 1
    return
  }
  const faceMatcher = new faceapi.FaceMatcher(faceResults) // --> Exception
```

```
Error: FaceRecognizer.constructor - expected inputs to be of type LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array | Array<LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array>

    at /Users/.../node_modules/face-api.js/src/globalApi/FaceMatcher.ts:40:13
    at Array.map (<anonymous>)
    at new FaceMatcher (/Users/.../node_modules/face-api.js/src/globalApi/FaceMatcher.ts:27:43)
    at ...
```

**Comment by chanduthedev** [comment]
I executed same code in my MacBook and it was working fine.
```
await faceapi.nets.ssdMobilenetv1.loadFromDisk('./weights')
await faceapi.nets.faceRecognitionNet.loadFromDisk('./weights')
await faceapi.nets.faceLandmark68Net.loadFromDisk('./weights')

const faceBase64 = 'data:image/jpg;base64,' + fs.readFileSync('resize/resize/10001/faces94.jpg', {encoding: 'base64'})
const faceImage = new Image()
faceImage.src = faceBase64
const res = await faceapi.detectAllFaces(faceImage).withFaceLandmarks().withFaceDescriptors()
const faceMatcher = new faceapi.FaceMatcher(res)
console.log('faceMatcher:',faceMatcher)
```

**Output:**
```
faceMatcher: FaceMatcher {
  _distanceThreshold: 0.6,
  _labeledDescriptors: [
    LabeledFaceDescriptors {
      _label: 'person 1',
      _descriptors: [Array]
    }
  ]
}
```
**Node version:** v12.14.1
**nmpm version:** 6.13.4

**Comment by chanduthedev** [comment]
I executed same code in my MacBook and it was working fine.
```
await faceapi.nets.ssdMobilenetv1.loadFromDisk('./weights')
await faceapi.nets.faceRecognitionNet.loadFromDisk('./weights')
await faceapi.nets.faceLandmark68Net.loadFromDisk('./weights')

const faceBase64 = 'data:image/jpg;base64,' + fs.readFileSync('faces94.jpg', {encoding: 'base64'})
const faceImage = new Image()
faceImage.src = faceBase64
const res = await faceapi.detectAllFaces(faceImage).withFaceLandmarks().withFaceDescriptors()
const faceMatcher = new faceapi.FaceMatcher(res)
console.log('faceMatcher:',faceMatcher)
```

**Output:**
```
faceMatcher: FaceMatcher {
  _distanceThreshold: 0.6,
  _labeledDescriptors: [
    LabeledFaceDescriptors {
      _label: 'person 1',
      _descriptors: [Array]
    }
  ]
}
```
**Node version:** v12.14.1
**nmpm version:** 6.13.4

**Comment by karthik-Gopalan** [comment]
I don't know how it's working in Mac, but you are missing a step after:

const faceResults = await faceapi.detectAllFaces(faceImage)
      .withFaceLandmarks()
      .withFaceDescriptors()

You have to get the labelled descriptors. It could look something like this: 

            const faceResults = await faceapi.detectAllFaces(img).withFaceLandmarks().withFaceDescriptors()
            if(faceResults ) {
                               descriptions = [faceResults .descriptor]
            }
            const singlelabeledDescriptor = new faceapi.LabeledFaceDescriptors(label,descriptions )

Let me know if this helps.

**Comment by chanduthedev** [comment]
Hi @Karthik-tr , 
thank you for pointing out. I also faced same error after adding your code. 
Actually `faceResults` is a list with one item and not a json object. So to access `descriptor`, you need to specify index like `faceResults[0].descriptor`

Try below code, it should work.

```
const faceResults = await faceapi.detectAllFaces(img).withFaceLandmarks().withFaceDescriptors()
if(faceResults ) {
   descriptions = [faceResults[0].descriptor]
}
const singlelabeledDescriptor = new faceapi.LabeledFaceDescriptors(label,descriptions )
```

**Comment by karthik-Gopalan** [comment]
Ah my use case was for single face detection and hence it was not an array. Missed that. Thanks for pointing it out. Glad it worked.

**Comment by chanduthedev** [comment]
If single face, api should be `detectSingleFace` instead of `detectAllFaces`. In that case, it may not return array and your suggested code may work for that.

**Comment by karthik-Gopalan** [comment]
Yes i use a single face detector. Hence I made the mistake of assuming that the descriptor only has one object. Mine works well. Thanks for the inputs
