### ISSUE TITLE
Property 'toBuffer' does not exist on type 'HTMLCanvasElement'

### ISSUE THREAD

**Issue by Karric** [justadudewhohacks/face-api.js#690]
Via NPM, i installed this project, ts-node, and typescript.

However, I'm getting the following error with faceLandmarkDetection.ts in examples-nodejs:

```
TSError: ⨯ Unable to compile TypeScript:
faceLandmarkDetection.ts:19:45 - error TS2339: Property 'toBuffer' does not exist on type 'HTMLCanvasElement'.

19   saveFile('faceLandmarkDetection.jpg', out.toBuffer('image/jpeg'))
                                               ~~~~~~~~

    at createTSError (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jasonford/Desktop/face-api.js-master/examples/examples-nodejs/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:139:27)
```

I tracked down the source file for the canvas creation method and I do see that toBuffer is part of the canvas class, so I'm not sure what's going on here.

I'm not too familiar with typescript, so I couldn't even expose the properties of the class to confirm that it's there.

**Comment by notchris** [comment]
I'm also curious as to why this happens
