### ISSUE TITLE
IONIC: faceapi.detectAllFaces "Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0."

### ISSUE THREAD

**Issue by AneudysOrtiz** [justadudewhohacks/face-api.js#692]
Hello I'm trying to detect faces in realtime using the device camera but in ionic. I replicated the example provided  [here](https://github.com/WebDevSimplified/Face-Detection-JavaScript), it works well in the browser with `ng serve`, but it fails when running in Android. It throws the following error when executing `faceapi.detectAllFaces()`

Any idea of what could be happening?

### Error 
```
E/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 39108 - Msg: ERROR Error: Uncaught (in promise): IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
        at http://localhost/default~pages-face-validation-face-validation-module~pages-identity-validation-identity-validation-module-es2015.js:4023:531954
        at Array.map (<anonymous>)
        at http://localhost/default~pages-face-validation-face-validation-module~pages-identity-validation-identity-validation-module-es2015.js:4023:531848
        at http://localhost/default~pages-face-validation-face-validation-module~pages-identity-validation-identity-validation-module-es2015.js:4023:1801
        at Object.next (http://localhost/default~pages-face-validation-face-validation-module~pages-identity-validation-identity-validation-module-es2015.js:4023:1906)
        at n (http://localhost/default~pages-face-validation-face-validation-module~pages-identity-validation-identity-validation-module-es2015.js:4023:677)
        at ZoneDelegate.invoke (http://localhost/polyfills-es2015.js:3470:30)
        at Object.onInvoke (http://localhost/vendor-es2015.js:62348:33)
        at ZoneDelegate.invoke (http://localhost/polyfills-es2015.js:3469:36)
        at Zone.run (http://localhost/polyfills-es2015.js:3229:47)
```

Here is my HTML

```html
<div id="container" #container>
    <video width="960" height="720" muted autoplay id="video"></video>
</div>
```

Heres is my TypeScript code: 

```typescript
import * as faceapi from '../../../assets/tfjs/face-api.min.js'
import { Plugins, FilesystemDirectory, FilesystemEncoding } from '@capacitor/core';
const { Filesystem } = Plugins;


async ngOnInit() {
    await this.loadModels();
  }

async loadModels() {
    //set path to load models
    let filePathRoot = 'http://localhost/assets/';
    // faceapi settings
    faceapi.env.monkeyPatch({
      readFile: filePath =>
        new Promise(resolve => {
          let fileExtension = filePath.split("?")[0].split(".").pop();
          let fileName = filePath.split("?")[0].split("/").pop();
          if (fileExtension === "json") {
            fetch(filePathRoot + fileName)
              .then((response) => {
                resolve(response.text());
              })
          } else {
           //Retrieving shard files from File system using Cordova Plugin
            Filesystem.readFile({
              path: fileName,
              directory: FilesystemDirectory.Documents,
              encoding: FilesystemEncoding.UTF16
            }).then(file => {
              const str = file.data;
              var buf = new ArrayBuffer(str.length * 2);
              var bufView = new Uint16Array(buf);
              for (var i = 0, strLen = str.length; i < strLen; i++) {
                bufView[i] = str.charCodeAt(i);
              }
              resolve(new Uint8Array(buf));
            })
          }
        }),
      Canvas: HTMLCanvasElement,
      Image: HTMLImageElement,
      ImageData: ImageData,
      Video: HTMLVideoElement,
      createCanvasElement: () => document.createElement("canvas"),
      createImageElement: () => document.createElement("img")
    });

   // load models for recognition
    await faceapi.nets.tinyFaceDetector.loadFromDisk(filePathRoot);
    await faceapi.nets.faceRecognitionNet.loadFromDisk(filePathRoot);
    await faceapi.nets.faceExpressionNet.loadFromDisk(filePathRoot);

    this.startVideo();
  }

 startVideo() {
    const video = document.getElementById("video") as HTMLVideoElement;
    const container = document.getElementById("container") as HTMLDivElement;

    video.onplaying = () => {
      console.log('Camera loaded')
      this.analyze(video, container);
    };

    navigator.mediaDevices.getUserMedia({
      audio: false,
      video: {
        width: { ideal: 960 },
        height: { ideal: 720 },
      }
    }).then((stream) => {
      video.srcObject = stream;
    }).catch((err0r) => {
      console.log(err0r)
      video.src = "assets/video-test.mp4";
      video.play();
    });
  }

 analyze(source: HTMLVideoElement | HTMLImageElement, content) {
    const canvas = faceapi.createCanvasFromMedia(source);
    content.append(canvas);
    const displaySize = { width: source.width, height: source.height }
    faceapi.matchDimensions(canvas, displaySize)
    this.intervalId = setInterval(async () => {
      console.log(source.height, source.width)
      const detections = await faceapi.detectAllFaces(source, new 
     faceapi.TinyFaceDetectorOptions()).withFaceExpressions(); //FAILS HERE
      console.log(JSON.stringify(detections))
      const resizedDetections = faceapi.resizeResults(detections, displaySize)
      canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)
      faceapi.draw.drawDetections(canvas, resizedDetections)
      faceapi.draw.drawFaceExpressions(canvas, resizedDetections)
    }, 100)
  }
```

**Comment by AneudysOrtiz** [comment]
The problem was caused because the model file wasn't being loaded correctly. Here is the right way to load it from local file in Capacitor.

```javascript
 Filesystem.readFile({
                path: fileName,
                directory: FilesystemDirectory.External
              }).then(file => {
                const byteCharacters = atob(file.data);
                const byteNumbers = new Array(byteCharacters.length);
                for (let i = 0; i < byteCharacters.length; i++) {
                  byteNumbers[i] = byteCharacters.charCodeAt(i);
                }
                const bufView = new Uint8Array(byteNumbers);
                resolve(bufView);
              })
```
