### ISSUE TITLE
examples-nodejs faceRecognition compiles but does not run

### ISSUE THREAD

**Issue by ndtreviv** [justadudewhohacks/face-api.js#708]
# Steps taken:

1. Clone the repo
2. cd face-api.js/examples/examples-nodejs
3. npm i
4. tsc faceRecognition.ts
5. node faceRecognition.js

# Expected Result:
The example should run successfully

# Actual Result:
Error:
```
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
2020-10-13 12:12:56.217201: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-13 12:12:56.239716: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x11965f6e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-13 12:12:56.239755: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(node:10073) UnhandledPromiseRejectionWarning: Error: TinyYolov2 - load model before inference
    at TinyFaceDetector.TinyYolov2Base.forwardInput (/Users/me/Documents/Development/node_modules/face-api.js/build/commonjs/tinyYolov2/TinyYolov2Base.js:89:19)
    at TinyFaceDetector.<anonymous> (/Users/me/Documents/Development/node_modules/face-api.js/build/commonjs/tinyYolov2/TinyYolov2Base.js:128:51)
    at step (/Users/me/Documents/Development/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/me/Documents/Development/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/me/Documents/Development/node_modules/tslib/tslib.js:112:62)
(node:10073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

# Environment:
**node version**: v10.22.0
**os**: Mac OS Catalina (10.15.7)

**Comment by QiuanLee** [comment]
I have the same problem who can help me

**Comment by ndtreviv** [comment]
@QiuanLee I ended up using a fork that was a lot more developed and therefore robust: https://github.com/vladmandic/face-api

Good luck.
