### ISSUE TITLE
Unable to run nodejs example (module not found)

### ISSUE THREAD

**Issue by manfromarce** [justadudewhohacks/face-api.js#745]
Hi, I tried to build and run the nodejs example following the instructions in Readme.MD, specifically:
```
cd face-api.js/examples/examples-nodejs
npm i
tsc faceDetection.ts
node faceDetection.js
```
It builds successfully (the 'tsc' command has been executed) but it doesn't run and returns an error on 'node' command.
At first it also gave me some errors on build (related to some dependencies' prerequisites) and I somehow fixed them,
what am I still missing?
The error message is:
```
C:\Users\User\Desktop\demo1\face-api.js\examples\examples-nodejs>node faceDetection.js
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Cannot find the specified module.
\\?\C:\Users\User\Desktop\demo1\face-api.js\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\User\Desktop\demo1\face-api.js\node_modules\@tensorflow\tfjs-node\dist\index.js:46:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```
Thanks to everyone who can help me fix this

**Comment by Jefry-nolastname** [comment]
Solution: move D:\TFJS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to D:\TFJS\node_modules\@tensorflow\tfjs-node\lib\napi-v6\
*ps napi-v6 could be v5 or else depending on version
