### ISSUE TITLE
Uncaught (in promise) Error: Box.constructor - expected box to be IBoundingBox | IRect, instead have {"left":0.15384615384615385,"top":null,"right":0.15384615384615385,"bottom":null}

### ISSUE THREAD

**Issue by iamSwaps** [justadudewhohacks/face-api.js#871]
Uncaught (in promise) Error: Box.constructor - expected box to be IBoundingBox | IRect, instead have {"left":0.15384615384615385,"top":null,"right":0.15384615384615385,"bottom":null}
at ff.lf (face-api.min.js:1:540088)
    at new ff (face-api.min.js:1:540496)
    at hg.<anonymous> (face-api.min.js:1:570989)
    at face-api.min.js:1:1933
    at Object.next (face-api.min.js:1:2038)
    at n (face-api.min.js:1:809)

Am I doing this wrong or is this an actual issue?

**Comment by alexrqs** [comment]
how did you solve this issue @iamSwaps ?

**Comment by edwardms** [comment]
I had the exact same problem and I solved it using node.js with express. You can get my repository from here [RealTimeFaceDetectionApp](https://github.com/edwardms/RealTimeFaceDetection). You will need a webcam in order to work or, if you have Windows 10, you can use Camo Studio from Microsoft Store which will use your smartphone camera as a webcam.
