### ISSUE TITLE
Running the nodejs example

### ISSUE THREAD

**Issue by jerryduncan** [justadudewhohacks/face-api.js#916]
Am finding issues running the nodejs example, after running npm install, then try to run `ts-node faceDetection.ts`  i get this error `C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
faceDetection.ts:1:26 - error TS2307: Cannot find module 'face-api.js' or its corresponding type declarations.

1 import * as faceapi from 'face-api.js';
                           ~~~~~~~~~~~~~
faceDetection.ts:5:16 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

5 async function run() {
                 ~~~

    at createTSError (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\USER\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2307, 2354 ]
}`

**Comment by angy71** [comment]
How the above issue was solved?
